### PR TITLE
created a helper named blurb to display hist data

### PR DESCRIPTION
**Pull request by snugthejoiner**
@Brit200313 My coverage is 75% because I created a helper named 'blurb' to handle the details of each historical event.

When I look at spec tests I still feel like I'm having a dream where I'm taking the final exam and I realize I've never come to a single class. So I need to spend some time on it.

### CODE REVIEW

**Comment by Brit200313** [comment]
@snugthejoiner I'm standing firmly on not merging in PRs that are below 80% coverage. I'd like you to try writing a helper spec. 

http://stackoverflow.com/questions/1996757/writing-a-spec-for-helper-with-ruby-on-rails-and-rspec

Let me know if you need help!

**Comment by Brit200313** [comment]
@snugthejoiner I just committed a passing Helper test and added Pry. By using Pry, I was able to step through your code to see what the test didn't work. Makes it so much easier. 

You're at 85% but I'd like to see those pending tests either removed or solved before I merge this. 

  1) HistoricalEvent add some examples to (or delete) /Users/brittanymartin/projects/snugthejoiner/theusthread/spec/models/historical_event_spec.rb
             # Not yet implemented
             # ./spec/models/historical_event_spec.rb:4

          2) Tag add some examples to (or delete) /Users/brittanymartin/projects/snugthejoiner/theusthread/spec/models/tag_spec.rb
             # Not yet implemented
             # ./spec/models/tag_spec.rb:4

          3) User add some examples to (or delete) /Users/brittanymartin/projects/snugthejoiner/theusthread/spec/models/user_spec.rb
             # Not yet implemented
             # ./spec/models/user_spec.rb:4

          4) historical_events/index.html.erb add some examples to (or delete) /Users/brittanymartin/projects/snugthejoiner/theusthread/spec/views/historical_events/index.html.erb_spec.rb
             # Not yet implemented
             # ./spec/views/historical_events/index.html.erb_spec.rb:4

Hint: better to solve them now when the app is simple. 

popkey

**Comment by snugthejoiner** [comment]
Thanks! Yes, Pry is really helpful. I have added it to my Rails App checklist.

Having an example to refer to will be helpful.

**Comment by snugthejoiner** [comment]
Oh, I'm pleasantly surprised I was so close with historical_helper.

**Comment by Brit200313** [comment]
@snugthejoiner you were quite close!

**Comment by Brit200313** [comment]
That sounds like a good stopping point then. If you add validations to those models, be sure to test them. Merging this PR in now.

**Comment by snugthejoiner** [comment]
Hooray!

**Pull request merged**
