### PR TITLE
fixed schema with drop, migrate, create to get rid of birthdate

### PR DESCRIPTION
**Pull request by snugthejoiner**
fixed the schema!

### CODE REVIEW

**Comment by Brit200313** [comment]
Sweeeeeeeet. You had this!

popkey

**Comment by snugthejoiner** [comment]
Interesting. So, I could do `git pull origin master` which would bring **master** up to date. Would I then *delete* my seed-data branch and create a new feature branch? Or would there be some way to keep that branch name and work on it? Perhaps I could do `git pull origin master` on both the **master** branch AND the *seed-data** branch.

**Comment by Brit200313** [comment]
You can stay on the seed-data branch and keep committing to it. You only need to pull master down if you plan on branching off from it again (aka you're done with seed-data and seed-data is fully merged into master). Even though I "deleted" this branch on Github, if you push from it locally, it will reappear on Github.

popkey

**Comment by snugthejoiner** [comment]
Brilliant!

**Pull request merged**
