### PR TITLE
Person model

### PR DESCRIPTION
**Pull request by snugthejoiner**
OK, so can we merge this one? Or was it basically merged locally at the beginning of our meeting and this can just be deleted? @Brit200313

### CODE REVIEW

**Comment by Brit200313** [comment]
This stuff hasn't been merged in yet. What is the Simplecov coverage currently?

**Comment by snugthejoiner** [comment]
Aargh, now my brain is hurting. I can't change to the **person-model** branch because of a difference in the Gemlock file. So when I run specs now I'm at 68% because my helper_spec isn't in the master branch.

The only thing that is ACTUALLY not covered is the historical_events_controller because index method isn't tested.

**Comment by snugthejoiner** [comment]
@Brit200313 Ok, I `stashed` the current state of **master** on my machine, switched to the local **person-model**, ran `rspec spec` and got 100% coverage. Can we merge, s'il vous plait?

**Comment by Brit200313** [comment]
@snugthejoiner It is :100: 

Here's me merging =>

popkey

**Comment by snugthejoiner** [comment]
Hooray!

**Pull request merged**
