### PR TITLE
Perfect crud

### PR DESCRIPTION
**Pull request by snugthejoiner**
CRUD is perfect, tests are not (78%). I'd love to make this the Master. Let me know.

### CODE REVIEW

**Comment by Brit200313** [comment]
All right, I'll allow it. Merging in.

**Comment by snugthejoiner** [comment]
Thanks!

**Comment by Brit200313** [comment]
@snugthejoiner your personal_event update test is failing because of:

    @person = Person.find(params[:personal_event][:person_id]) in the personal_event controller (line 36)

you don't need to find the person in an update, just the event. Remove that line and change the test to: 

    post :update, id: @personal_event.id, personal_event: {description: "MyNewString"}, format: :json

Should pass!

**Comment by snugthejoiner** [comment]
Ooh, thanks. OK, I'm going to push some changes and do another PR; just tweaked the **notice/alert** on all the pages. Then I'll fix this next branch

**Pull request merged**
