### PR TITLE
Controllers and views

### PR DESCRIPTION
**Pull request by snugthejoiner**
Alright, I am at **exactly** 80% coverage!

I seemed to have learned a bit with the tests. Right now it looks to me like, for instance, `update` is working in terms of the action itself but after it updates, when it comes time to **save** it doesn't like my *test_personal_event* `test_personal_event = PersonalEvent.create`. Perhaps it is because it is `create` instead of `new`?!

```
Failure/Error: get :update, id:test_personal_event
ActionController::ParameterMissing:
param is missing or the value is empty: personal_event
```

### CODE REVIEW

**Comment by Brit200313** [comment]
@snugthejoiner did you try stepping through it with binding.pry? When a test fails, I'll bind it and see why it yells by copying and pasting it line by line. For this one, you are missing a param. 
Bind in the actual model and see what param it wants by running the app in realtime. Let me know that makes sense! To me, it is the key to debugging.

**Comment by snugthejoiner** [comment]
Right! I keep forgetting to use binding.pry
I will do so tomorrow. Thanks.

**Comment by snugthejoiner** [comment]
@Brit200313 I've been bogged down with day job work today. Can you merge this even though it's only at 80%. I'm going to be off the grid until Sunday (campingin Pemaquid, ME) but I'll be bringing the laptop and may be able to get some work done. I'd love to work on a new branch with **master** up to date.

**Comment by Brit200313** [comment]
Sure! As long as you pinkie swear to fix the broken test. 

Have a good trip! 

popkey

**Comment by snugthejoiner** [comment]
Pinky promise! THanks!

**Pull request merged**
